// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXse5aS_WDKuA-O4i0hbx1oBuO_71u_g',
    appId: '1:321064125566:web:68b78c2c8759f80a41442f',
    messagingSenderId: '321064125566',
    projectId: 'ngo-app-b2cd8',
    authDomain: 'ngo-app-b2cd8.firebaseapp.com',
    storageBucket: 'ngo-app-b2cd8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEtb82jdiio79orevzqraQNwFnO24G19I',
    appId: '1:321064125566:android:30b7087b8596735441442f',
    messagingSenderId: '321064125566',
    projectId: 'ngo-app-b2cd8',
    storageBucket: 'ngo-app-b2cd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstrrVyve9GUaO-XRKF_mvYlA-1BYuNt4',
    appId: '1:321064125566:ios:94251cafd9bcb34241442f',
    messagingSenderId: '321064125566',
    projectId: 'ngo-app-b2cd8',
    storageBucket: 'ngo-app-b2cd8.firebasestorage.app',
    iosBundleId: 'com.example.ngoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstrrVyve9GUaO-XRKF_mvYlA-1BYuNt4',
    appId: '1:321064125566:ios:94251cafd9bcb34241442f',
    messagingSenderId: '321064125566',
    projectId: 'ngo-app-b2cd8',
    storageBucket: 'ngo-app-b2cd8.firebasestorage.app',
    iosBundleId: 'com.example.ngoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATXse5aS_WDKuA-O4i0hbx1oBuO_71u_g',
    appId: '1:321064125566:web:f9ea668628db27a941442f',
    messagingSenderId: '321064125566',
    projectId: 'ngo-app-b2cd8',
    authDomain: 'ngo-app-b2cd8.firebaseapp.com',
    storageBucket: 'ngo-app-b2cd8.firebasestorage.app',
  );
}
